version: "3.7"

services:
  db:
    image: postgres:14-alpine
    container_name: sample_strapi_db
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./docker_volumes/pgdata:/var/lib/postgresql/data
