version: "3.7"

services:
  app:
    build: .
    container_name: sample_strapi
    restart: unless-stopped
    env_file: .env
    networks:
      - sample_strapi_network
    volumes:
      - ./docker_volumes/strapi_uploads:/app/public/uploads:Z
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: sample_strapi_db
    restart: unless-stopped
    env_file: .env
    networks:
      - sample_strapi_network
    volumes:
      - ./docker_volumes/pgdata:/var/lib/postgresql/data

networks:
  sample_strapi_network:
