version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sample_strapi
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - sample_strapi_network
    volumes:
      - ./:/app/dev:Z
      - ignore:/app/dev/node_modules
    ports:
      - 8000:1337
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: sample_strapi_db
    restart: unless-stopped
    env_file: .env
    networks:
      - sample_strapi_network
    volumes:
      - ./docker_volumes/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  sample_strapi_network:

volumes:
  ignore:
